[[redirects]]
  from = "/parenting-who"
  to = "https://parenting-who-covid-19-act.netlify.com"
  status = 301

[[redirects]]
  from = "/follow"
  to = "https://follow-covid-19-act.netlify.com"
  status = 301

[[redirects]]
  from = "/publish"
  to = "https://publish-covid-19-act.netlify.com"
  status = 301

[[redirects]]
  from = "/portal"
  to = "https://portal-covid-19-act.netlify.com"
  status = 301
