[[redirects]]
  from = "/"
  to = "/parenting-who/"
  status = 302
  force = true

[[redirects]]
  from = "/parenting-who/*"
  to = "https://parenting-who-covid-19-act.netlify.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/follow/*"
  to = "https://follow-covid-19-act.netlify.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/publish/*"
  to = "https://publish-covid-19-act.netlify.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/portal/*"
  to = "https://portal-covid-19-act.netlify.com/:splat"
  status = 200
  force = true
